package com.zlx.user.dal.mapper;

import com.zlx.user.dal.model.DeviceDO;
import com.zlx.user.dal.model.DeviceDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeviceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sat Aug 18 16:15:55 CST 2018
     */
    int countByExample(DeviceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sat Aug 18 16:15:55 CST 2018
     */
    int deleteByExample(DeviceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sat Aug 18 16:15:55 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sat Aug 18 16:15:55 CST 2018
     */
    int insert(DeviceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sat Aug 18 16:15:55 CST 2018
     */
    int insertSelective(DeviceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sat Aug 18 16:15:55 CST 2018
     */
    List<DeviceDO> selectByExample(DeviceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sat Aug 18 16:15:55 CST 2018
     */
    DeviceDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sat Aug 18 16:15:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") DeviceDO record, @Param("example") DeviceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sat Aug 18 16:15:55 CST 2018
     */
    int updateByExample(@Param("record") DeviceDO record, @Param("example") DeviceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sat Aug 18 16:15:55 CST 2018
     */
    int updateByPrimaryKeySelective(DeviceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbggenerated Sat Aug 18 16:15:55 CST 2018
     */
    int updateByPrimaryKey(DeviceDO record);
}