package com.zlx.user.dal.model;

public class DeviceDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.id
     *
     * @mbggenerated Sat Aug 18 16:15:55 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_id
     *
     * @mbggenerated Sat Aug 18 16:15:55 CST 2018
     */
    private String deviceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.id
     *
     * @return the value of device.id
     *
     * @mbggenerated Sat Aug 18 16:15:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.id
     *
     * @param id the value for device.id
     *
     * @mbggenerated Sat Aug 18 16:15:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_id
     *
     * @return the value of device.device_id
     *
     * @mbggenerated Sat Aug 18 16:15:55 CST 2018
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_id
     *
     * @param deviceId the value for device.device_id
     *
     * @mbggenerated Sat Aug 18 16:15:55 CST 2018
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }
}